# SINGLE NEURON

In [5]:
import torch
import numpy as np

In [2]:
def activation(x):
    return 1/(1+torch.exp(-x))

In [18]:
torch.manual_seed(7)
features = torch.randn((1,5))
weights = torch.randn_like(features)
bias = torch.randn((1,1))

In [19]:
#y = activation(torch.sum(features * weights) + bias)
#y = activation((features * weights).sum() + bias)
y = activation(torch.mm(features, weights.view(5, 1)) + bias)

### STACK

In [3]:
torch.manual_seed(7)
features = torch.randn((1, 3))
print(features)
n_input = features.shape[1]
n_hidden = 2
n_output = 1
W1 = torch.randn(n_input, n_hidden)
W2 = torch.randn(n_hidden, n_output)
B1 = torch.randn(1, n_hidden)
B2 = torch.randn(1, n_output)

h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)
print(output)

tensor([[-0.1468,  0.7861,  0.9468]])
tensor([[0.3171]])


### Numpy and Torch

In [6]:
a = np.random.rand(4, 3)
a

array([[0.37559616, 0.87972059, 0.33112371],
       [0.58220482, 0.59978104, 0.85831592],
       [0.36615525, 0.27041913, 0.67710546],
       [0.26851308, 0.36697808, 0.71303329]])

In [8]:
b = torch.from_numpy(a)
b

tensor([[0.3756, 0.8797, 0.3311],
        [0.5822, 0.5998, 0.8583],
        [0.3662, 0.2704, 0.6771],
        [0.2685, 0.3670, 0.7130]], dtype=torch.float64)

In [9]:
b.numpy()

array([[0.37559616, 0.87972059, 0.33112371],
       [0.58220482, 0.59978104, 0.85831592],
       [0.36615525, 0.27041913, 0.67710546],
       [0.26851308, 0.36697808, 0.71303329]])

b.mul_(2)

In [11]:
a

array([[0.75119231, 1.75944118, 0.66224742],
       [1.16440964, 1.19956209, 1.71663184],
       [0.7323105 , 0.54083826, 1.35421093],
       [0.53702617, 0.73395615, 1.42606657]])

They shared memory,a in numpy,b in torch